### ISSUE TITLE
Kept saying a error

### ISSUE THREAD

**Issue by gamer167** [DELUUXE/DiscordChroma#19]
Error when started and is not working

**Comment by gamer167** [comment]
Yes latter.

**Comment by gamer167** [comment]
[13:07:25:086] [info] checking for updates
[13:07:25:091] [info] Checking for update
[13:07:25:097] [info] starting DiscordChroma
[13:07:26:812] [info] Update for version 0.4.10 is not available (latest version: 0.4.10, downgrade is disallowed).
[13:07:27:883] [info] There has been an error!
[13:07:27:889] [error] {
  constructor: 'FetchError',
  message: 'request to http://localhost:54235/razer/chromasdk failed, reason: connect ECONNREFUSED 127.0.0.1:54235',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  stack: 'FetchError: request to http://localhost:54235/razer/chromasdk failed, reason: connect ECONNREFUSED 127.0.0.1:54235\n' +
    '    at ClientRequest.<anonymous> (D:\\Program files\\Discord Chroma\\DiscordChroma\\resources\\app.asar\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n' +
    '    at ClientRequest.emit (events.js:203:13)\n' +
    '    at Socket.socketErrorListener (_http_client.js:399:9)\n' +
    '    at Socket.emit (events.js:203:13)\n' +
    '    at emitErrorNT (internal/streams/destroy.js:91:8)\n' +
    '    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:77:11)'
}

**Comment by gamer167** [comment]
How do I install that?

**Comment by DELUUXE** [comment]
at: https://www.razer.com/eu-en/synapse-3

**Comment by gamer167** [comment]
When I am done it still does not open it does not give a error tho.

**Comment by gamer167** [comment]
[17:12:56:630] [info] checking for updates
[17:12:56:635] [info] Checking for update
[17:12:56:641] [info] starting DiscordChroma
[17:13:00:781] [info] Update for version 0.4.10 is not available (latest version: 0.4.10, downgrade is disallowed).
[17:13:15:784] [info] changed client id to 882368120755474502
[17:13:28:770] [info] changed client secret

**Comment by DELUUXE** [comment]
Yes to which question?
Could you provide more information?
Its quite hard to find the issue without enough information.

**Comment by DELUUXE** [comment]
Closing due to inactivity.
